# Generated by Django 6.0.4 on 2026-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateField(help_text='Preferred pickup or event date.'),
        ),
    ]
